language: objective-c
before_install:
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-testtap
  - brew tap --repair
env:
  - PACKAGE=upspin
script:
  - brew audit --except=specs $PACKAGE
  - brew install --devel --verbose $PACKAGE
  - brew test $PACKAGE
